### ISSUE TITLE
Encryption page under Monitoring crashes even with user with full access

### ISSUE THREAD

**Issue by harshavardhana** [minio/console#2701]
```
:9443/api/v1/kms/metrics:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
react-dom.production.min.js:189 TypeError: Cannot read properties of null (reading 'map')
    at me (Status.tsx:216:41)
    at Ei (react-dom.production.min.js:167:137)
    at Tl (react-dom.production.min.js:197:258)
    at _s (react-dom.production.min.js:292:88)
    at bc (react-dom.production.min.js:280:389)
    at gc (react-dom.production.min.js:280:320)
    at vc (react-dom.production.min.js:280:180)
    at ac (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
fl @ react-dom.production.min.js:189
react-dom.production.min.js:283 Uncaught TypeError: Cannot read properties of null (reading 'map')
    at me (Status.tsx:216:41)
    at Ei (react-dom.production.min.js:167:137)
    at Tl (react-dom.production.min.js:197:258)
    at _s (react-dom.production.min.js:292:88)
    at bc (react-dom.production.min.js:280:389)
    at gc (react-dom.production.min.js:280:320)
    at vc (react-dom.production.min.js:280:180)
    at ac (react-dom.production.min.js:271:88)
    at oc (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
:9443/api/v1/kms/apis:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:9443/api/v1/kms/version:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

Resulting in Console UI blank page.  

Reproduced on v0.25.0

At the same time, however `Encryption` tab to lookup keys works fine.

**Comment by cesnietor** [comment]
we'll verify if it's already fix.
